version: '3'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - .:/code
    - logvolume:/var/log
    depends_on:
    - nosql
    - redis
    - memcache
  nosql:
    image: "cassandra:3.0"
  redis:
    image: "redis:alpine"
  memcache:
    image: "memcached:alpine"

volumes:
  logvolume: {}
