version: '1'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - .:/code
    - logvolume:/var/log
    links:
    - mongo
    - redis
    - mq
    - memcache
  mongo:
    image: "mongo"
  redis:
    image: "redis:alpine"
  mq:
    image: "rabbitmq:alpine"
  memcache:
    image: "memcached:alpine"

volumes:
  logvolume: {}
