version: '3'
services:
  web:
    build: .
    image: "django_vulnerable"
    ports:
    - "8000:8000"
    volumes:
    - .:/code
    - logvolume:/var/log
    depends_on:
    - nosql
    - redis
    - memcache
    working_dir: /code
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  nosql:
    image: "cassandra:3.0"
  redis:
    image: "redis:4.0-alpine"
  memcache:
    image: "memcached:1.5-alpine"

volumes:
  logvolume: {}
